// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNX-zAPAEU7rI0TffDOQhPjC77q45Xirg',
    appId: '1:835296411177:web:644443ba8da4b408a92638',
    messagingSenderId: '835296411177',
    projectId: 'klapp-5a43c',
    authDomain: 'klapp-5a43c.firebaseapp.com',
    storageBucket: 'klapp-5a43c.appspot.com',
    measurementId: 'G-84ZJX35RYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa739W5hjUC-utLV0AVmk1thpc8qWZOkE',
    appId: '1:835296411177:android:2e02904ce8bee6a1a92638',
    messagingSenderId: '835296411177',
    projectId: 'klapp-5a43c',
    storageBucket: 'klapp-5a43c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdmlRGGcrCAbH7O6dYnkhb7EY8quUBxa0',
    appId: '1:835296411177:ios:4fc93066b6c0a2cfa92638',
    messagingSenderId: '835296411177',
    projectId: 'klapp-5a43c',
    storageBucket: 'klapp-5a43c.appspot.com',
    iosClientId: '835296411177-3i6ek5ao2828dspfk8trdbb4skps5ll2.apps.googleusercontent.com',
    iosBundleId: 'com.example.klapp02',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdmlRGGcrCAbH7O6dYnkhb7EY8quUBxa0',
    appId: '1:835296411177:ios:4fc93066b6c0a2cfa92638',
    messagingSenderId: '835296411177',
    projectId: 'klapp-5a43c',
    storageBucket: 'klapp-5a43c.appspot.com',
    iosClientId: '835296411177-3i6ek5ao2828dspfk8trdbb4skps5ll2.apps.googleusercontent.com',
    iosBundleId: 'com.example.klapp02',
  );
}
